"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import BootstrapClient from "./(components)/clinetComponent/page";
import NavBar from "./(components)/navBar/page";
import Footer from "./(components)/footer/page";
import { StoreProvider } from "@/store/StoreProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AnimatePresence, motion } from "framer-motion";
import { useId } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  let id = useId();
  return (
    <html lang="en">
      <body>
        <SpeedInsights></SpeedInsights>
        <NavBar></NavBar>
        <StoreProvider>
          <AnimatePresence mode="awit">
            <motion.div key={id}> {children}</motion.div>
          </AnimatePresence>
        </StoreProvider>
        <Footer></Footer>
        <BootstrapClient />
      </body>
    </html>
  );
}
